### PR TITLE
Pull request from oros.

### PR DESCRIPTION
**Pull request by oros**
Augmented BBM sample with Invoke functionality; now with appropriate licensing.

### CODE REVIEW

**Comment by pelegri** [comment]
I think the CC3.0-BY icon library requires a reference to the author, probably in a NOTICE file.  I'll mail you and Richard in a sec to cover the topic, OK?  Hopefully we can resolve it and approve it tomorrow. / cc @timwindsor

**Comment by timwindsor** [comment]
Checkout the license file for the sensors sample. It has a section for the icons at the end

Tim

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by oros** [comment]
Will update the request soon. Fixing the noted licensing and adding  a NOTICE file.

**Comment by oros** [comment]
Just running one last set of tests, but are the LICENSE and NOTICE files currently being used as we want them? Any changes that would need to be added there? Please let me know.

Once I finish up my tests on the current code, I'll post here and (barring other changes) should be good to go.

**Comment by oros** [comment]
Hello all, unless there are any outstanding licensing issues, I'm good to go from a functionality point on this sample.

**Comment by pelegri** [comment]
All good to go.  Could you add it to the Samples Catalog as a pull request on [Catalogs](http://github.com/blackberry/Catalogs)  See these [Draft Instructions](http://pelegri.github.com/Catalogs/Add_Sample.html)

**Comment by oros** [comment]
Will do.

**Pull request merged**
