### PR TITLE
Added Avatar-Booth Sample

### PR DESCRIPTION
**Pull request by anzorb**
Added getUserMedia sample App.

### CODE REVIEW

**Comment by anzorb** [comment]
This has gotten OSS approval from Richard.

**Comment by pelegri** [comment]
OK.  And you and @timwindsor agree you want it here, not in BB10-WebWorks-Community-Samples?  Note that means you are committing to keeping this up-to-date for all releases.

**Comment by anzorb** [comment]
I intend on keeping this up to date with the public build releases. I just realized that I commended out code that does work on the public build. I will close this and reissue a pull request with the changes.

**Comment by pelegri** [comment]
OK.

BTW, I believe that if you submit a new pull request it will be combined with this one and a single merge will get all the updates that are pending at the time.

**Comment by timwindsor** [comment]
Actually, it's anything that you push to your repo on the same branch, while a pull request is open.

**Comment by pelegri** [comment]
Good to know, Tim.

**Pull request closed without merging**
