### PR TITLE
Built-For-BlackBerry: viewport setup

### PR DESCRIPTION
**Pull request by miamon**
Not necessary viewport setup, since bbui.js version 0.9.4 are adding this at runtime based on the OS version, see changelog

https://github.com/blackberry/bbUI.js/blob/2979720c51da953d92c5e31cc0658036cbe57e1a/CHANGELOG.md

### CODE REVIEW

**Comment by pelegri** [comment]
@astanley and @ctetreault - you OK with this one?  I'd love to merge Josep's change in /cc @miamon

**Comment by ctetreault** [comment]
yup, pretty sure it's accurate according to Tim Neil's docs on bbUI

**Comment by pelegri** [comment]
might as well add Mr @tneil

**Comment by tneil** [comment]
So is this just picking up the latest bbUI that handles the viewport settings?

**Comment by ctetreault** [comment]
Yep.

**Comment by tneil** [comment]
cool

**Pull request merged**
