### PR TITLE
CSS fixes

### PR DESCRIPTION
**Pull request by listedegarde**
Removed extra curly brace in /Avatar-Booth/scripts/pages/takePhotoView/style-hdpi.css and removed space between li :first-child in /UI-Layouts/common/style.css

### CODE REVIEW

**Comment by listedegarde** [comment]
@timwindsor Thanks for the help earlier today!  Did I do that right?  And why do I have two different profiles (Jonathan and listedegarde)?

**Comment by timwindsor** [comment]
Looks good, and this fix is small enough that we can accept without the ICLA signed

You've got 2 profiles, because listedegarde is your github account, where the pull request and any comments come from. But, Jonathan is what Git on your local machine is using when it does a commit. You can edit those settings using git tools (command line, tortoise-git, or other) so that they match up.

**Comment by listedegarde** [comment]
Thank you!  I actually have signed the ICLA, I think it was that one anyway.  I'm in the list here: http://blackberry.github.io/approvedSignatories.html as Jonathan Frazer.  The linked GitHub account is this one.

Thank you also for explaining the two profiles.  I think I have it straight now, but I'll find out when I push something else to GitHub.

**Comment by timwindsor** [comment]
Thanks, sorry I missed that before.

**Pull request merged**
