### PR TITLE
Fixed a small CSS bug

### PR DESCRIPTION
**Pull request by listedegarde**
Should I have to do this twice since there are two branches?  I already submitted this fix for the master branch.  This is what I did:
1. Created 2 additional forks on my local repository: listedegarde from the master, and listedegarde-2.0 from WebWorks-2.0
2. Made the changes in each branch, and then committed the changes.
3. Pushed the changes to the origin (my fork on Github)
4. Sent 2 pull requests back to BlackBerry.

I think I'm starting to get the hang of it, but please let me know if I did something wrong, or if there is anything I should improve upon in my process.

### CODE REVIEW

**Comment by listedegarde** [comment]
Also, I'm guessing that commits wouldn't normally be this small?  But I'm trying to make sure I understand the principles before doing something big.  Thanks!

**Comment by timwindsor** [comment]
Yes, that process is the ideal approach for doing a fix. For most ones of this size you could do it easier, but that's the really proper way to do so when you have much more detailed updates to do.

**Comment by listedegarde** [comment]
Thank you!  Is this what I should do now?
1. Delete my branches on GitHub using the blue button above.
2. Delete the branches from on my local machine (since all updates have now been included in the merge to BlackBerry's repository)
3. Switch to my Master branch on my local machine
4. Pull from the BlackBerry GitHub repository remote Master
5. Repeat steps 3 and 4 for the Webworks-2.0 branch as well
6. Push my updated branches to my origin to update my GitHub.

It seems like quite a few steps, especially the loop in 5, but I don't see a simpler way of doing it.  After that, I should be ready to create another branch on my local machine to repeat the process of submitting an improvement, eh?

**Comment by timwindsor** [comment]
That's pretty much the flow. There are short cuts you can do, and some tools like SourceTree speed things up as well. But that's the core of what you would be doing.

**Pull request merged**
