### PR TITLE
Sample injection extension plus example on BlackBerry website

### PR DESCRIPTION
**Pull request by ejzn**

### CODE REVIEW

**Comment by pelegri** [comment]
Can @timwindsor do a tech review?
On my side, we follow the best-practice of including the LICENSE in the sample directory; that way if somebody copy-pastes just that directory, they get the LICENSE with it.   Can you add that?   Plus the usual internal review.

**Comment by ejzn** [comment]
Yup a license I I easy thin to add :)

**Comment by timwindsor** [comment]
Good to go, just waiting on the license.

**Comment by astanley** [comment]
/bump Erik?  Also I notice some copyright headers have 2012, should be 2013 for all.

**Comment by ejzn** [comment]
Will updated, sorry for the delay.

**Comment by ejzn** [comment]
@pelegri Updated license. @astanley updated year in the copyright headers.

**Pull request merged**
