### PR TITLE
config.xml, copy paste error?

### PR DESCRIPTION
**Pull request by rodnolan**

### CODE REVIEW

**Comment by kwallis** [comment]
Adam, are you comfortable with this pull request and want to merge?

**Comment by timwindsor** [comment]
Rod,
Looks like you've been pushing to the same branch that where you had this pull request open and there's a queue of commits built up now. We can't automatically merge it, but there's a lot here that we could use I think. Can you update your repository to match the latest and make sure that all the commits are ones that you want to provide?

**Comment by rodnolan** [comment]
Doing that now.

**Comment by rodnolan** [comment]
Tim, I have done

git fetch upstream
git merge upstream/master

and fixed a couple of conflicts but my fork's source is still very
different from upstream. I've got to pack up for the day but over the
weekend I'll do a new commit on a new branch which will contain the one
(very small) change I intended to commit and do another pull request with
just that commit.

I think the key is to put that commit on a separate branch to avoid further
confusion, correct?

**Comment by rodnolan** [comment]
Just wondering if you can cherry-pick it?

https://github.com/rodnolan/BB10-WebWorks-Samples/commit/80f1d6ef2e40c15bf2be613288fce03f0d197f59

**Comment by timwindsor** [comment]
Best thing is to close this request and open a new one on a different branch that contains just the change you want. Some of your other changes might be included later when you've had time to work on them. 

I'd cherry pick it, but I want you to get credit for the pull request since I'm not certain how we are going to track these things.

**Comment by cdelcol** [comment]
This might help sort things out for you...
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

It lets you apply your commits on top of a branch (like master), rather than merging. It puts the onus on the incoming code/change to be clean and provides a nice neat linear history once it gets merged back to master. Work like this:
1. Create branch
2. Do work
3. Rebase to a single commit (1 item per branch) and force push back to same branch
4. Code review/Pull request
5. Code changes
6. Repeat 3 - 5 as necessary
7. Merge feature into master

Hope this helps.

**Comment by rodnolan** [comment]
new pull request submitted with a single commit

**Comment by rodnolan** [comment]
Thanks, @cdelcol... still learning git on the fly so this is good information for the future.

**Pull request closed without merging**
