### PR TITLE
Web works 2.0

### PR DESCRIPTION
**Pull request by listedegarde**
Trying to get the WebWorks 2.0 branch from BlackBerry's onto mine.

### CODE REVIEW

**Comment by timwindsor** [comment]
If you've forked the repository, and cloned it to your local machine, just checkout the origin/WebWorks-2.0 branch. That should be all you need to do, to see the new samples.

**Comment by timwindsor** [comment]
If you've got an older copy, and you want to update it, set up the blackberry repository as an additional remote, then checkout the blackberry/WebWorks-2.0 branch (assuming you called the new remote "blackberry").

**Comment by listedegarde** [comment]
Thank you for your help! As you can see, I'm still trying to learn. Sorry for whatever I just did (I think I tried to merge my master onto the blackberry/WebWorks-2.0?). I'm just starting to read the git-scm book to try to understand. I was trying to do both the things that you suggested: update my master and download the 2.0. If you don't mind, I have a few questions.   
1. If I checkout the blackberry/WebWorks-2.0 branch on my local machine, will that automatically add it to my github.com web version's fork?
2. Will all changes on my local machine be automatically reflected on my github.com fork?
3. If I want to submit a pull request to BlackBerry (that means suggest an update, right?), is creating my own fork the right way of doing things?  Do I need my own fork on my github.com, or should I be pulling and pushing and yanking and thrusting directly from the blackberry github on my local computer? I don't really need my own version of the repository, except obviously for my local machine where I'm making bug fixes to suggest to BlackBerry. 
4. Is there anything that you would suggest for learning github? The git-scm book seems to be for gît in general, but I really want to learn how to use github as well. Github's "learn" page says that the content is deprecated, and suggests their YouTube channel. I only see 3 vidéos that will be useful for me. I'll watch them, but I'm wondering if there might be anything else.

I have versioning working on my local computer: I can make and delete branches, merge them back to my master branch, check in and out of branches, make tags, etc. The part I'm really trying to figure out is github.com. Anyway, sorry again for whatever foolishness I just tried to do. Someday, somehow, I will get this straight. I've been trying on and off since I joined github, but I'm not going to give up.

**Comment by timwindsor** [comment]
Sorry for the delay, I intended to get back to you earlier, but was busy on the weekend. Here's some answers and suggestions:
1. No, but after you do that checkout, you can do a push to your GitHub remote and it will update the fork with this branch.
2. No, each fork (or clone) is an entirely independent repository, with ways to link any of them together through "remotes". A remote doesn't typically work like a mirror though - it requires pushes and pulls to move commits around.
3. Only a few people have access to push code directly into the BlackBerry repository - it's a lot safer that way. What you want to do is fork the repository to your account on GitHub, then clone from there. Then it's recommended that you create a branch for your new contributions - and when you're ready, push that branch to your GitHub repository. From there you can create a pull request back to BlackBerry. A pull request allows us to review the code and comment on it before it get's accepted. Also, anything you push to that branch while a pull request is open will become part of the request. That makes it really easy to make little tweaks if you've done your work on separate branches.
4. I read the git-scm book and it's a good base. There's a good bit in there that I don't really use that often though. I did a youtube video specific to BlackBerry that I hope you will find very useful - if not, let me know so I can fix it :) 
   http://www.youtube.com/watch?v=mJH0uPaChL8

Thanks for your interest. I'll do my best to help you along.

**Pull request closed without merging**
